name: Bug report
description: Create a report to help us improve
title: "[Bug]"
labels:
  - bug
assignees: AndersonHJB
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: |-
        确保您遵循这些声明。（不然作者可能会把Fxxx的话扔给你）
      options:
        - label: 我阅读了常见问题: [https://bornforthis.cn/1v1/02-yuebao/#Question](https://bornforthis.cn/1v1/02-yuebao/#Question)
          required: true

        - label: I am using the **latest v2 version** of VuePress and VuePress official plugins.
          required: true

        - label: I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
          required: true

        - label: I am following the docs and I am sure I am using the correct configuration.
          required: true

        - label: I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)
          required: true

  - type: input
    id: package
    attributes:
      label: Package name
      description: Which package are you reporting
      value: vuepress-theme-hope
      placeholder: package name
    validations:
      required: true

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating system are you using?
      description: You may select more than one. Don’t select anything if it's not about the environment.
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  - type: markdown
    attributes:
      value: |
        ## Describe the bug

        > If applicable, add screenshots and log to help explain your problem.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: If you are not reporting something obvious, a minimal reproduction repo and related log is required.
      placeholder: Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuration.
